name: benchmark

on:
  push:
    branches:
      - master

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
      - name: Benchmark
        run: |
          export BETTERSTACK_TOKEN=${{ secrets.BETTERSTACK_TOKEN }}
          curl -sL https://github.com/${GITHUB_REPOSITORY}/raw/master/README.md | \
          awk '{if($0 ~ "// go test -v"){a=1;b=1};if($0 ~ "```" && b=1){b=0};if (a&&b) {print}}' | \
          tee log_test.go
          export GOPROXY=direct
          go mod init main
          go get github.com/${GITHUB_REPOSITORY}@master
          go get github.com/rs/zerolog
          go get go.uber.org/zap
          head -1 log_test.go | cut -b3- | sed -E 's#\r##' | bash -xe
